package com.productys.poc.composite.divers;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class TestPanelVertical extends CustomComponent {

	@AutoGenerated
  private AbsoluteLayout mainLayout;
	@AutoGenerated
  private VerticalLayout verticalLayout_1;
	@AutoGenerated
  private Button button_2;
	@AutoGenerated
  private Panel panel_1;
	@AutoGenerated
  private VerticalLayout verticalLayout_2;
	@AutoGenerated
  private Button button_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TestPanelVertical() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
  private AbsoluteLayout buildMainLayout() {
	  // common part: create layout
	  mainLayout = new AbsoluteLayout();
	  mainLayout.setImmediate(false);
	  mainLayout.setWidth("100%");
	  mainLayout.setHeight("100%");
	  mainLayout.setMargin(false);
	  
	  // top-level component properties
	  setWidth("100.0%");
	  setHeight("100.0%");
	  
	  // verticalLayout_1
	  verticalLayout_1 = buildVerticalLayout_1();
	  mainLayout.addComponent(verticalLayout_1, "top:40.0px;left:60.0px;");
	  
	  return mainLayout;
  }

	@AutoGenerated
  private VerticalLayout buildVerticalLayout_1() {
	  // common part: create layout
	  verticalLayout_1 = new VerticalLayout();
	  verticalLayout_1.setImmediate(false);
	  verticalLayout_1.setWidth("140px");
	  verticalLayout_1.setHeight("340px");
	  verticalLayout_1.setMargin(false);
	  
	  // button_1
	  button_1 = new Button();
	  button_1.setCaption("Button");
	  button_1.setImmediate(false);
	  button_1.setWidth("-1px");
	  button_1.setHeight("-1px");
	  verticalLayout_1.addComponent(button_1);
	  verticalLayout_1.setComponentAlignment(button_1, new Alignment(48));
	  
	  // panel_1
	  panel_1 = buildPanel_1();
	  verticalLayout_1.addComponent(panel_1);
	  verticalLayout_1.setExpandRatio(panel_1, 1.0f);
	  
	  // button_2
	  button_2 = new Button();
	  button_2.setCaption("Button");
	  button_2.setImmediate(false);
	  button_2.setWidth("-1px");
	  button_2.setHeight("-1px");
	  verticalLayout_1.addComponent(button_2);
	  verticalLayout_1.setComponentAlignment(button_2, new Alignment(48));
	  
	  return verticalLayout_1;
  }

	@AutoGenerated
  private Panel buildPanel_1() {
	  // common part: create layout
	  panel_1 = new Panel();
	  panel_1.setImmediate(false);
	  panel_1.setWidth("100.0%");
	  panel_1.setHeight("100.0%");
	  
	  // verticalLayout_2
	  verticalLayout_2 = new VerticalLayout();
	  verticalLayout_2.setImmediate(false);
	  verticalLayout_2.setWidth("-1px");
	  verticalLayout_2.setHeight("-1px");
	  verticalLayout_2.setMargin(false);
	  panel_1.setContent(verticalLayout_2);
	  
	  return panel_1;
  }

}
