package com.productys.poc.composite.divers;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.VerticalLayout;

public class TestCentPercentComposite extends CustomComponent {

	@AutoGenerated
  private AbsoluteLayout mainLayout;
	@AutoGenerated
  private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
  private VerticalLayout verticalLayout_3;
	@AutoGenerated
  private VerticalLayout verticalLayout_1;
	@AutoGenerated
  private VerticalLayout verticalLayout_2;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TestCentPercentComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
  private AbsoluteLayout buildMainLayout() {
	  // common part: create layout
	  mainLayout = new AbsoluteLayout();
	  mainLayout.setImmediate(false);
	  mainLayout.setWidth("100%");
	  mainLayout.setHeight("100%");
	  mainLayout.setMargin(false);
	  
	  // top-level component properties
	  setWidth("100.0%");
	  setHeight("100.0%");
	  
	  // horizontalLayout_1
	  horizontalLayout_1 = buildHorizontalLayout_1();
	  mainLayout.addComponent(horizontalLayout_1, "top:40.0px;left:40.0px;");
	  
	  return mainLayout;
  }

	@AutoGenerated
  private HorizontalLayout buildHorizontalLayout_1() {
	  // common part: create layout
	  horizontalLayout_1 = new HorizontalLayout();
	  horizontalLayout_1.setStyleName("horizGlobal");
	  horizontalLayout_1.setImmediate(false);
	  horizontalLayout_1.setWidth("760px");
	  horizontalLayout_1.setHeight("320px");
	  horizontalLayout_1.setMargin(true);
	  
	  // verticalLayout_2
	  verticalLayout_2 = new VerticalLayout();
	  verticalLayout_2.setStyleName("vert1");
	  verticalLayout_2.setImmediate(false);
	  verticalLayout_2.setWidth("100.0%");
	  verticalLayout_2.setHeight("100.0%");
	  verticalLayout_2.setMargin(false);
	  horizontalLayout_1.addComponent(verticalLayout_2);
	  horizontalLayout_1.setExpandRatio(verticalLayout_2, 1.0f);
	  
	  // verticalLayout_1
	  verticalLayout_1 = new VerticalLayout();
	  verticalLayout_1.setStyleName("vert2");
	  verticalLayout_1.setImmediate(false);
	  verticalLayout_1.setWidth("100.0%");
	  verticalLayout_1.setHeight("100.0%");
	  verticalLayout_1.setMargin(false);
	  horizontalLayout_1.addComponent(verticalLayout_1);
	  horizontalLayout_1.setExpandRatio(verticalLayout_1, 1.0f);
	  
	  // verticalLayout_3
	  verticalLayout_3 = new VerticalLayout();
	  verticalLayout_3.setStyleName("vert3");
	  verticalLayout_3.setImmediate(false);
	  verticalLayout_3.setWidth("100.0%");
	  verticalLayout_3.setHeight("100.0%");
	  verticalLayout_3.setMargin(false);
	  horizontalLayout_1.addComponent(verticalLayout_3);
	  horizontalLayout_1.setExpandRatio(verticalLayout_3, 1.0f);
	  
	  return horizontalLayout_1;
  }

}
