package com.productys.poc.composite.divers;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class TestForm extends CustomComponent {

	@AutoGenerated
  private AbsoluteLayout mainLayout;
	@AutoGenerated
  private GridLayout gridLayout_1;
	@AutoGenerated
  private TextField textField_1;
	@AutoGenerated
  private Label label_5;
	@AutoGenerated
  private CheckBox checkBox_2;
	@AutoGenerated
  private Label label_4;
	@AutoGenerated
  private TextField textField_2;
	@AutoGenerated
  private Label label_3;
	@AutoGenerated
  private ComboBox comboBox_1;
	@AutoGenerated
  private Label label_2;
	@AutoGenerated
  private CheckBox checkBox_1;
	@AutoGenerated
  private Label label_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TestForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
  private AbsoluteLayout buildMainLayout() {
	  // common part: create layout
	  mainLayout = new AbsoluteLayout();
	  mainLayout.setImmediate(false);
	  mainLayout.setWidth("100%");
	  mainLayout.setHeight("100%");
	  mainLayout.setMargin(false);
	  
	  // top-level component properties
	  setWidth("100.0%");
	  setHeight("100.0%");
	  
	  // gridLayout_1
	  gridLayout_1 = buildGridLayout_1();
	  mainLayout.addComponent(gridLayout_1);
	  
	  return mainLayout;
  }

	@AutoGenerated
  private GridLayout buildGridLayout_1() {
	  // common part: create layout
	  gridLayout_1 = new GridLayout();
	  gridLayout_1.setImmediate(false);
	  gridLayout_1.setSizeFull();
	  gridLayout_1.setMargin(false);
	  gridLayout_1.setStyleName("gridLayout_1");
	  gridLayout_1.setColumns(2);
	  gridLayout_1.setRows(5);
	  
	  // label_1
	  label_1 = new Label();
	  label_1.setImmediate(false);
	  label_1.setWidth("100.0%");
	  label_1.setHeight("-1px");
	  label_1.setValue("Position eprouvette conforme");
	  gridLayout_1.addComponent(label_1, 0, 0);
	  
	  // checkBox_1
	  checkBox_1 = new CheckBox();
	  checkBox_1.setCaption("CheckBox");
	  checkBox_1.setImmediate(false);
	  checkBox_1.setWidth("-1px");
	  checkBox_1.setHeight("-1px");
	  gridLayout_1.addComponent(checkBox_1, 1, 0);
	  
	  // label_2
	  label_2 = new Label();
	  label_2.setImmediate(false);
	  label_2.setWidth("100.0%");
	  label_2.setHeight("-1px");
	  label_2.setValue("Position eprouvette conforme");
	  gridLayout_1.addComponent(label_2, 0, 1);
	  
	  // comboBox_1
	  comboBox_1 = new ComboBox();
	  comboBox_1.setImmediate(false);
	  comboBox_1.setWidth("-1px");
	  comboBox_1.setHeight("-1px");
	  gridLayout_1.addComponent(comboBox_1, 1, 1);
	  
	  // label_3
	  label_3 = new Label();
	  label_3.setImmediate(false);
	  label_3.setWidth("100.0%");
	  label_3.setHeight("-1px");
	  label_3.setValue("Position eprouvette conforme");
	  gridLayout_1.addComponent(label_3, 0, 2);
	  
	  // textField_2
	  textField_2 = new TextField();
	  textField_2.setImmediate(false);
	  textField_2.setWidth("-1px");
	  textField_2.setHeight("-1px");
	  textField_2.setSecret(false);
	  gridLayout_1.addComponent(textField_2, 1, 2);
	  
	  // label_4
	  label_4 = new Label();
	  label_4.setImmediate(false);
	  label_4.setWidth("100.0%");
	  label_4.setHeight("-1px");
	  label_4.setValue("Position eprouvette conforme");
	  gridLayout_1.addComponent(label_4, 0, 3);
	  
	  // checkBox_2
	  checkBox_2 = new CheckBox();
	  checkBox_2.setCaption("CheckBox");
	  checkBox_2.setImmediate(false);
	  checkBox_2.setWidth("-1px");
	  checkBox_2.setHeight("-1px");
	  gridLayout_1.addComponent(checkBox_2, 1, 3);
	  
	  // label_5
	  label_5 = new Label();
	  label_5.setImmediate(false);
	  label_5.setWidth("100.0%");
	  label_5.setHeight("-1px");
	  label_5.setValue("Position eprouvette conforme");
	  gridLayout_1.addComponent(label_5, 0, 4);
	  
	  // textField_1
	  textField_1 = new TextField();
	  textField_1.setImmediate(false);
	  textField_1.setWidth("-1px");
	  textField_1.setHeight("-1px");
	  textField_1.setSecret(false);
	  gridLayout_1.addComponent(textField_1, 1, 4);
	  
	  return gridLayout_1;
  }

}
