package com.productys.poc.composite.divers;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;

public class TestScrollPanelComposite extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TestScrollPanelComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new AbsoluteLayout();
		
		final Panel panel = new Panel("Scrolling Panel");
		panel.setHeight("300px");
		panel.setWidth("400px");
		panel.getContent().setHeight("1000px");
		panel.setScrollable(true);
		        
		mainLayout.addComponent(panel);

		HorizontalLayout scrollButtons = new HorizontalLayout();
		mainLayout.addComponent(scrollButtons);
		        
		Button scrollUp = new Button("Scroll Up");
		scrollUp.addListener(new Button.ClickListener() {
		    public void buttonClick(ClickEvent event) {
		        int scrollPos = panel.getScrollTop() - 250;
		        if (scrollPos < 0)
		            scrollPos = 0;
		        panel.setScrollTop(scrollPos);
		    }
		});
		scrollButtons.addComponent(scrollUp);
		        
		Button scrollDown = new Button("Scroll Down");
		scrollDown.addListener(new Button.ClickListener() {
		    public void buttonClick(ClickEvent event) {
		        int scrollPos = panel.getScrollTop();
		        if (scrollPos > 1000)
		            scrollPos = 1000;
		        panel.setScrollTop(scrollPos + 250);
		    }
		});
		scrollButtons.addComponent(scrollDown);
		scrollButtons.addComponent(new Button("Scroll Down"));
		scrollButtons.addComponent(new Button("Scroll Down"));
		scrollButtons.addComponent(new Button("Scroll Down"));
		scrollButtons.addComponent(new Button("Scroll Down"));
		scrollButtons.addComponent(new Button("Scroll Down"));
	}

}
