package com.productys.poc.composite.eworkshop;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Tree;
import com.vaadin.ui.VerticalLayout;

public class EworkshopPoc1 extends CustomComponent {

	@AutoGenerated
  private AbsoluteLayout mainLayout;

	@AutoGenerated
  private HorizontalSplitPanel horizontalSplitPanel_Op;

	@AutoGenerated
  private GridLayout gridLayout_Media;

	@AutoGenerated
  private GridLayout gridLayout_Documents;

	@AutoGenerated
  private VerticalLayout verticalLayout_Validation;

	@AutoGenerated
  private Embedded embedded_Media;

	@AutoGenerated
  private Label label_Media;

	@AutoGenerated
  private VerticalLayout verticalLayout_Op;

	@AutoGenerated
  private VerticalLayout verticalLayout_AutoControles;

	@AutoGenerated
  private HorizontalLayout horizontalLayout_Boutons;

	@AutoGenerated
  private Button button_4;

	@AutoGenerated
  private Button button_3;

	@AutoGenerated
  private Button button_2;

	@AutoGenerated
  private VerticalLayout verticalLayout_Images;

	@AutoGenerated
  private TextArea textArea_Description;

	@AutoGenerated
  private Label label_OpActuelle;

	@AutoGenerated
  private VerticalLayout verticalLayout_Ops;

	@AutoGenerated
  private Tree tree_Ops;

	@AutoGenerated
  private HorizontalLayout horizontalLayout_EnteteGlobal;

	@AutoGenerated
  private Button button_Quitter;

	@AutoGenerated
  private HorizontalLayout horizontalLayout_Entete;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public EworkshopPoc1() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
  private AbsoluteLayout buildMainLayout() {
	  // common part: create layout
	  mainLayout = new AbsoluteLayout();
	  mainLayout.setImmediate(false);
	  mainLayout.setWidth("100%");
	  mainLayout.setHeight("100%");
	  mainLayout.setMargin(false);
	  
	  // top-level component properties
	  setWidth("100.0%");
	  setHeight("100.0%");
	  
	  // horizontalLayout_EnteteGlobal
	  horizontalLayout_EnteteGlobal = buildHorizontalLayout_EnteteGlobal();
	  mainLayout.addComponent(horizontalLayout_EnteteGlobal,
	      "top:0.0px;left:0.0px;");
	  
	  // verticalLayout_Ops
	  verticalLayout_Ops = buildVerticalLayout_Ops();
	  mainLayout.addComponent(verticalLayout_Ops, "top:60.0px;left:0.0px;");
	  
	  // horizontalSplitPanel_Op
	  horizontalSplitPanel_Op = buildHorizontalSplitPanel_Op();
	  mainLayout.addComponent(horizontalSplitPanel_Op,
	      "top:60.0px;right:2.0px;bottom:-3.0px;left:200.0px;");
	  
	  return mainLayout;
  }

	@AutoGenerated
  private HorizontalLayout buildHorizontalLayout_EnteteGlobal() {
	  // common part: create layout
	  horizontalLayout_EnteteGlobal = new HorizontalLayout();
	  horizontalLayout_EnteteGlobal.setStyleName("horizontalLayout_EnteteGlobal");
	  horizontalLayout_EnteteGlobal.setImmediate(false);
	  horizontalLayout_EnteteGlobal.setWidth("100.0%");
	  horizontalLayout_EnteteGlobal.setHeight("60px");
	  horizontalLayout_EnteteGlobal.setMargin(false);
	  
	  // horizontalLayout_Entete
	  horizontalLayout_Entete = new HorizontalLayout();
	  horizontalLayout_Entete.setImmediate(false);
	  horizontalLayout_Entete.setWidth("100.0%");
	  horizontalLayout_Entete.setHeight("100.0%");
	  horizontalLayout_Entete.setMargin(false);
	  horizontalLayout_EnteteGlobal.addComponent(horizontalLayout_Entete);
	  horizontalLayout_EnteteGlobal.setExpandRatio(horizontalLayout_Entete, 1.0f);
	  
	  // button_Quitter
	  button_Quitter = new Button();
	  button_Quitter.setCaption("Quitter");
	  button_Quitter.setImmediate(true);
	  button_Quitter.setWidth("-1px");
	  button_Quitter.setHeight("-1px");
	  horizontalLayout_EnteteGlobal.addComponent(button_Quitter);
	  horizontalLayout_EnteteGlobal.setComponentAlignment(button_Quitter,
	      new Alignment(34));
	  
	  return horizontalLayout_EnteteGlobal;
  }

	@AutoGenerated
  private VerticalLayout buildVerticalLayout_Ops() {
	  // common part: create layout
	  verticalLayout_Ops = new VerticalLayout();
	  verticalLayout_Ops.setStyleName("verticalLayout_Ops");
	  verticalLayout_Ops.setImmediate(false);
	  verticalLayout_Ops.setWidth("200px");
	  verticalLayout_Ops.setHeight("100.0%");
	  verticalLayout_Ops.setMargin(false);
	  
	  // tree_Ops
	  tree_Ops = new Tree();
	  tree_Ops.setImmediate(false);
	  tree_Ops.setWidth("100.0%");
	  tree_Ops.setHeight("100.0%");
	  verticalLayout_Ops.addComponent(tree_Ops);
	  verticalLayout_Ops.setExpandRatio(tree_Ops, 1.0f);
	  
	  return verticalLayout_Ops;
  }

	@AutoGenerated
  private HorizontalSplitPanel buildHorizontalSplitPanel_Op() {
	  // common part: create layout
	  horizontalSplitPanel_Op = new HorizontalSplitPanel();
	  horizontalSplitPanel_Op.setImmediate(false);
	  horizontalSplitPanel_Op.setWidth("100.0%");
	  horizontalSplitPanel_Op.setHeight("100.0%");
	  horizontalSplitPanel_Op.setMargin(false);
	  
	  // verticalLayout_Op
	  verticalLayout_Op = buildVerticalLayout_Op();
	  horizontalSplitPanel_Op.addComponent(verticalLayout_Op);
	  
	  // gridLayout_Media
	  gridLayout_Media = buildGridLayout_Media();
	  horizontalSplitPanel_Op.addComponent(gridLayout_Media);
	  
	  return horizontalSplitPanel_Op;
  }

	@AutoGenerated
  private VerticalLayout buildVerticalLayout_Op() {
	  // common part: create layout
	  verticalLayout_Op = new VerticalLayout();
	  verticalLayout_Op.setImmediate(false);
	  verticalLayout_Op.setWidth("100.0%");
	  verticalLayout_Op.setHeight("100.0%");
	  verticalLayout_Op.setMargin(false);
	  
	  // label_OpActuelle
	  label_OpActuelle = new Label();
	  label_OpActuelle.setStyleName("label_OpActuelle");
	  label_OpActuelle.setImmediate(false);
	  label_OpActuelle.setWidth("100.0%");
	  label_OpActuelle.setHeight("20px");
	  label_OpActuelle.setValue("Opération actuelle");
	  verticalLayout_Op.addComponent(label_OpActuelle);
	  
	  // textArea_Description
	  textArea_Description = new TextArea();
	  textArea_Description.setStyleName("textArea_Description");
	  textArea_Description.setImmediate(false);
	  textArea_Description.setWidth("100.0%");
	  textArea_Description.setHeight("214px");
	  verticalLayout_Op.addComponent(textArea_Description);
	  
	  // verticalLayout_2
	  verticalLayout_Images = new VerticalLayout();
	  verticalLayout_Images.setImmediate(false);
	  verticalLayout_Images.setWidth("100.0%");
	  verticalLayout_Images.setHeight("-1px");
	  verticalLayout_Images.setMargin(false);
	  verticalLayout_Images.setStyleName("verticalLayout_Images");
	  verticalLayout_Op.addComponent(verticalLayout_Images);
	  
	  // horizontalLayout_Boutons
	  horizontalLayout_Boutons = buildHorizontalLayout_Boutons();
	  verticalLayout_Op.addComponent(horizontalLayout_Boutons);
	  
	  // verticalLayout_AutoControles
	  verticalLayout_AutoControles = new VerticalLayout();
	  verticalLayout_AutoControles.setStyleName("verticalLayout_AutoControles");
	  verticalLayout_AutoControles.setImmediate(false);
	  verticalLayout_AutoControles.setWidth("100.0%");
	  verticalLayout_AutoControles.setHeight("194px");
	  verticalLayout_AutoControles.setMargin(false);
	  verticalLayout_Op.addComponent(verticalLayout_AutoControles);
	  
	  return verticalLayout_Op;
  }

	@AutoGenerated
  private HorizontalLayout buildHorizontalLayout_Boutons() {
	  // common part: create layout
	  horizontalLayout_Boutons = new HorizontalLayout();
	  horizontalLayout_Boutons.setStyleName("horizontalLayout_Boutons");
	  horizontalLayout_Boutons.setImmediate(false);
	  horizontalLayout_Boutons.setWidth("100.0%");
	  horizontalLayout_Boutons.setHeight("65px");
	  horizontalLayout_Boutons.setMargin(false);
	  
	  // button_2
	  button_2 = new Button();
	  button_2.setCaption("Opérations");
	  button_2.setImmediate(true);
	  button_2.setWidth("-1px");
	  button_2.setHeight("-1px");
	  horizontalLayout_Boutons.addComponent(button_2);
	  horizontalLayout_Boutons.setComponentAlignment(button_2, new Alignment(48));
	  
	  // button_3
	  button_3 = new Button();
	  button_3.setCaption("Légendes");
	  button_3.setImmediate(true);
	  button_3.setWidth("-1px");
	  button_3.setHeight("-1px");
	  horizontalLayout_Boutons.addComponent(button_3);
	  horizontalLayout_Boutons.setComponentAlignment(button_3, new Alignment(48));
	  
	  // button_4
	  button_4 = new Button();
	  button_4.setCaption("Annexes");
	  button_4.setImmediate(true);
	  button_4.setWidth("-1px");
	  button_4.setHeight("-1px");
	  horizontalLayout_Boutons.addComponent(button_4);
	  horizontalLayout_Boutons.setComponentAlignment(button_4, new Alignment(48));
	  
	  return horizontalLayout_Boutons;
  }

	@AutoGenerated
  private GridLayout buildGridLayout_Media() {
	  // common part: create layout
	  gridLayout_Media = new GridLayout();
	  gridLayout_Media.setImmediate(false);
	  gridLayout_Media.setWidth("100.0%");
	  gridLayout_Media.setHeight("100.0%");
	  gridLayout_Media.setMargin(false);
	  gridLayout_Media.setColumns(2);
	  gridLayout_Media.setRows(3);
	  
	  // label_Media
	  label_Media = new Label();
	  label_Media.setStyleName("label_Media");
	  label_Media.setImmediate(false);
	  label_Media.setWidth("100.0%");
	  label_Media.setHeight("100.0%");
	  label_Media.setValue("Label");
	  gridLayout_Media.addComponent(label_Media, 1, 0);
	  
	  // embedded_Media
	  embedded_Media = new Embedded();
	  embedded_Media.setStyleName("embedded_Media");
	  embedded_Media.setImmediate(false);
	  embedded_Media.setWidth("100.0%");
	  embedded_Media.setHeight("100.0%");
	  embedded_Media.setSource(new ThemeResource(
	      "img/component/embedded_icon.png"));
	  embedded_Media.setType(1);
	  embedded_Media.setMimeType("image/png");
	  gridLayout_Media.addComponent(embedded_Media, 1, 1);
	  
	  // verticalLayout_Validation
	  verticalLayout_Validation = new VerticalLayout();
	  verticalLayout_Validation.setStyleName("verticalLayout_Validation");
	  verticalLayout_Validation.setImmediate(false);
	  verticalLayout_Validation.setWidth("-1px");
	  verticalLayout_Validation.setHeight("100.0%");
	  verticalLayout_Validation.setMargin(false);
	  gridLayout_Media.addComponent(verticalLayout_Validation, 0, 2);
	  
	  // gridLayout_Documents
	  gridLayout_Documents = new GridLayout();
	  gridLayout_Documents.setStyleName("gridLayout_Documents");
	  gridLayout_Documents.setImmediate(false);
	  gridLayout_Documents.setWidth("100.0%");
	  gridLayout_Documents.setHeight("100.0%");
	  gridLayout_Documents.setMargin(false);
	  gridLayout_Media.addComponent(gridLayout_Documents, 1, 2);
	  
	  return gridLayout_Media;
  }

}
